# Generated by Django 4.2.3 on 2023-11-23 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlecategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='selected_categories',
        ),
        migrations.AddField(
            model_name='article',
            name='selected_categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='article.articlecategory', verbose_name='دسته بندی ها'),
            preserve_default=False,
        ),
    ]
