# Generated by Django 4.2.3 on 2023-11-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_selected_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='selected_categories',
        ),
        migrations.AddField(
            model_name='article',
            name='selected_categories',
            field=models.ManyToManyField(related_name='category', to='article.articlecategory', verbose_name='دسته بندی ها'),
        ),
    ]
