# Generated by Django 4.2.3 on 2023-11-26 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('article', '0005_alter_articlecomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picture', to='media.image'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='media.image'),
        ),
    ]
