# Generated by Django 4.2.7 on 2023-11-20 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=200, unique=True, verbose_name='عنوان در url')),
                ('price', models.BigIntegerField(verbose_name='قیمت')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.image')),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'خدمات ها',
            },
        ),
    ]
