# Generated by Django 4.2.7 on 2023-11-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_time', models.DateTimeField(verbose_name='تاریخ پایان ')),
                ('saleable_seats', models.IntegerField(verbose_name='صندلی های قابل فروش')),
                ('Services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showTime', to='service.services')),
            ],
            options={
                'verbose_name': 'سانس',
                'verbose_name_plural': 'سانس ها',
            },
        ),
    ]
