# Generated by Django 4.2.7 on 2023-11-20 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('service', '0003_remove_showtime_saleable_seats_showtime_num_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='cover',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='media.image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='service.services')),
            ],
            options={
                'ordering': ('display_order',),
            },
        ),
    ]
