# Generated by Django 4.2.7 on 2023-11-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('service', '0005_services_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ServicesImage',
        ),
    ]
