# Generated by Django 4.2.7 on 2023-11-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('service', '0008_alter_servicesimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagess', to='media.image', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='servicesimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='service.services'),
        ),
    ]
