# Generated by Django 4.2.7 on 2023-11-17 20:23

from django.db import migrations, models
import user.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('Phone', 'Phone'), ('E-Mail', 'Email')], default='Phone', max_length=10)),
                ('receiver', models.CharField(max_length=50)),
                ('password', models.CharField(default=user.models.generate_otp, max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
