# Generated by Django 4.2.7 on 2023-11-17 20:23

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_otprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='password',
            field=models.CharField(default=user.models.generate_otp, max_length=6),
        ),
    ]
